Added AlternativePatternStmt type - no parsing, no sema, no codegen
bcardosolopes/llvm-project pull request #11
Opened 2021-02-15 08:00 UTC by idiv0

Added AlternativePatternStmt type, along with associated enums and methods in JSON printers, AST parsing etc.

The AlternativePatternStmt is mostly a copy of ExpressionPatternStmt, with minor changes so it is detected as the correct type in `classof()`.

2021-02-16 11:18 UTC, idiv0 commented on clang/lib/Analysis/CFG.cpp
> +  return nullptr;
The implementations of the other VisitPattern* funcitons, like `VisitExpressionPatternStmt` all just return `nullptr` so this is currently consistent with those. Should they all have an `assert`?

2021-02-16 11:25 UTC, idiv0 commented on clang/include/clang/ASTMatchers/ASTMatchers.h
> +// TODO Document this
Ok, I think I understand what it should be with the syntax change. Something like this ok?
```
/// Matches alternative pattern statements inside inspect expressions.
///
/// Given
/// \code
///   inspect(a) { b => x(); 0 => y(); <T> __ => z() }
/// \endcode
/// AlternativePatternStmt()
///   matches '<T>:'.
```

2021-02-16 11:27 UTC, idiv0 commented on clang/include/clang/ASTMatchers/ASTMatchers.h
> +// TODO Are above comments correct? Are the colons old syntax and should be
Ok, I'm happy to fix this while I'm here. Not a big scope and confirming that helped me understand what these comments mean.

2021-02-16 11:27 UTC, dansarginson commented on clang/lib/Analysis/CFG.cpp
> +  return nullptr;
Hmm, good point. We should probably stay consistent for now.

2021-02-16 11:33 UTC, idiv0 commented on clang/include/clang/AST/Stmt.h
> +  static ExpressionPatternStmt *Create(const ASTContext &Ctx,
Should be an AlternativePatternStmt

2021-02-16 11:34 UTC, idiv0 commented on clang/include/clang/AST/Stmt.h
> +  /// Build an empty expression pattern statement.
/// Build an alternative pattern statement

2021-02-16 21:36 UTC, idiv0 commented on clang/include/clang/ASTMatchers/ASTMatchers.h
> +// TODO Are above comments correct? Are the colons old syntax and should be
I decided to fix the other comments whilst I was here.

2021-02-19 00:16 UTC, bcardosolopes commented
Hi @idiv0, thanks for working on this. I like that you are adding the scaffolding first, that should make it easier to review later patches. General comments before I dive into other details, can you please:
- Split out functionality that it's not related to separate PRs (thanks for fixing those comments)
- Squash all commits on this PR into one and force push, I rather see 1-1 commit-PR relationship for tracking history easier.
- Please provide your name so I can add proper credits when I upstream to the LLVM org.
- Rebase your changes and add a case in the proper switch on CFG.cpp for the alternative pattern, no need to implement it right now.

2021-02-19 21:12 UTC, idiv0 commented
Hi @bcardosolopes, I think I have addressed all the issues. I will fix the comment changes in a separate PR.

2021-02-19 21:59 UTC, bcardosolopes reviewed
Great. On a side note, if you want to fix `StmtProfiler::VisitStructuredBindingPatternStmt`, `TextNodeDumper::VisitStructuredBindingPatternStmt`, and overall structured bindings support in `ASTMatchers/ASTMatchersInternal.cpp` and `ASTMatchers/Dynamic/Registry.cpp` in another PR that would be great.

2021-02-19 21:59 UTC, bcardosolopes commented on clang/include/clang/AST/Stmt.h
> +    return matchCondOffset() + hasPatternGuard();
Returning `NumMandatoryStmtPtr` should be enough here.

2021-02-19 21:59 UTC, bcardosolopes commented on clang/include/clang/AST/Stmt.h
> +      setPatternGuard(Guard);
I've recently simplified this, you can mimic the other patterns.

2021-02-19 21:59 UTC, bcardosolopes commented on clang/lib/AST/StmtPrinter.cpp
> +void StmtPrinter::VisitAlternativePatternStmt(AlternativePatternStmt *Node) {
This also recently changed for other patterns, need to update!

2021-02-19 21:59 UTC, bcardosolopes commented on clang/lib/AST/StmtProfile.cpp
> +void StmtProfiler::VisitAlternativePatternStmt(
Can you move this past the Structured Binding one?

2021-02-19 21:59 UTC, bcardosolopes commented on clang/tools/libclang/CXCursor.cpp
> -
Looks like your editor decided to trim off whitespaces here, please fix this to only contain the relevant change.

2021-02-20 15:29 UTC, idiv0 commented on clang/include/clang/AST/Stmt.h
> +      setPatternGuard(Guard);
Copied the new pattern.

2021-02-20 15:32 UTC, idiv0 commented on clang/tools/libclang/CXCursor.cpp
> -
Frustrating settings, sorry! Fixed the IDE settings and reverted the whitespace changes.

2021-02-21 09:04 UTC, idiv0 commented
Thanks @bcardosolopes I've updated the code for this and created a PR for adding structured bindings to AST bits and pieces
https://github.com/bcardosolopes/llvm-project/pull/12/

2021-02-22 21:47 UTC, bcardosolopes reviewed
Almost there, thanks for your patience. Can you also a description to your commit message saying what is and what's not being added? The title should probably also be "[PatternMatching] Add skeleton for Alternative Pattern support" or something along those lines.

2021-02-22 21:47 UTC, bcardosolopes commented on clang/include/clang/AST/Stmt.h
> +    setPatternGuard(Guard);
Can you make this the first fn call?

2021-02-22 21:47 UTC, bcardosolopes commented on clang/include/clang/AST/Stmt.h
> +  unsigned patternGuardOffset() const {
Is this clang formatted?

2021-02-22 21:47 UTC, bcardosolopes commented on clang/include/clang/AST/Stmt.h
> +    return AP->hasPatternGuard();
Nice cleanup, can you split that out into another patch? I'd prefer if this contains only AlternativePatternStmt related changes.

2021-02-23 18:41 UTC, idiv0 commented on clang/include/clang/AST/Stmt.h
> +  unsigned patternGuardOffset() const {
Yes, I've just run it again on the new set of changes and it came out the same. I guess it must be just over the line length?

2021-02-23 18:41 UTC, idiv0 commented on clang/include/clang/AST/Stmt.h
> +    return AP->hasPatternGuard();
Yes, removed all the `const` on this method so it is consistently non-const. 

I will create a new PR after this has been merged in to make them all const.

2021-02-23 18:53 UTC, idiv0 commented
I've updated the title and the commit message. Hopefully it is enough detail. Also made the changes requested 😄

2021-02-23 18:57 UTC, dansarginson commented
LGTM, but Bruno is the merge approver 👍

2021-03-01 19:50 UTC, bcardosolopes requested changes
Getting close, one more remaining change!

2021-03-01 19:50 UTC, bcardosolopes commented on clang/include/clang/AST/Stmt.h
> +        reinterpret_cast<Stmt *>(Guard);
You missing a `InspectPatternBits.PatternStmtHasPatternGuard = Guard ? true : false;` here.

2021-03-01 21:41 UTC, bcardosolopes approved these changes

2021-03-01 21:41 UTC, merged