[CIR][WIP] RecordDecl
bcardosolopes/llvm-project pull request #32
Opened 2021-12-09 02:15 UTC by lanza

Still need to work on a few things, figured I'd put it up to look at for now.

2021-12-09 02:21 UTC, lanza commented on clang/lib/CIR/CIRBuilder.cpp
> +    case Decl::CXXRecord: {
Need to `assert(false)` this until the rest of the CXXRecord asserts are fixed.

2021-12-09 02:21 UTC, lanza commented on clang/lib/CIR/CIRBuilder.cpp
> +  mlir::FuncOp emitFunction(const FunctionDecl *FD) {
Need to rename this to `buildFunction`

2021-12-09 02:21 UTC, lanza commented on clang/lib/CIR/CIRBuilder.cpp
> +    builder->emitTopLevelDecl(*I);
`buildTopLevelDecl`

2021-12-09 02:21 UTC, lanza commented on clang/lib/CIR/CIRGenTypes.cpp
> +  // ty->setName(outStream.str());
Should the name be an `attr` for the struct type?

2021-12-09 02:21 UTC, lanza commented on clang/lib/CIR/CIRGenTypes.cpp
> +    addRecordTypeName(recordDecl, entry, "");
This needs to be moved to after `computeRecordLayout`

2021-12-09 02:21 UTC, lanza commented on clang/test/CIR/CodeGen/struct.cir
> +module  {
delete dis

2021-12-09 02:21 UTC, lanza commented on mlir/lib/Dialect/CIR/IR/CIRTypes.cpp
> +  if (mnemonic == "struct") {
This is kinda sloppy, rewrite this.

2021-12-09 02:21 UTC, lanza commented on mlir/lib/Dialect/CIR/IR/CIRTypes.cpp
> +  }
elif

2021-12-09 07:51 UTC, bcardosolopes requested changes
Amazing progress, excited for this!

I think we would benefit from a smaller patch to build on top, there's too much stuff being introduced that don't contribute to the struct "hello world". I'm always down to leaving paths that hit an assert for unimplemented, but I'm not getting a clear sense of unimplemented paths as I read through the patch, which makes it hard to review. One example is `CIRBitFieldInfo`, does it really need to be part of this time around?

Some comments inline but a few overall design points I've got:
- Is the layout caching necessary? How it works when names gets introduced? Maybe MLIR already does it? I know it does that it uniques source locations for instance. LLVM doesn't care about type info, maybe that's why only the layout is tracked.
- It would be nice to have the name info out of the box.
- I'd suggest we keep capital names for things we are copying from codegeinfo. For example I noticed `CIRBitFieldInfo` members got lowered, I see we having lots of trouble in the future rewriting all of this because we factored out things upstream and since they are shared with Clang's regular LLVM codegen they will likely stay capitalized. I know this is a weird place to be, my general fuzzy rule has been: if it's related to emit/building AST I'm mostly using LLVM style, when it's creating/dealing with mlir types/ops, I use lower - it's a shitty system so I won't get picky on that.

More comments inline!

2021-12-09 07:51 UTC, bcardosolopes commented on clang/lib/CIR/CIRGenTypes.cpp
> +  // ty->setName(outStream.str());
Yes, one option is to add one `StringAttr` input operand to the StructType

2021-12-09 07:51 UTC, bcardosolopes commented on clang/lib/CIR/CIRGenTypes.cpp
> +
Can you remove this empty line?

2021-12-09 07:51 UTC, bcardosolopes commented on clang/lib/CIR/CIRGenTypes.cpp
> +      // || !ty->isOpaque() //
Leaving these empty if bodies around can get tricky later when we miss to emit what was needed, can you put an assert here and everywhere else where this happens?

2021-12-09 07:51 UTC, bcardosolopes commented on clang/lib/CIR/CIRGenTypes.cpp
> +    return entry;
If the idea is to return this early might be better to remove all the code below and insert an assert after the return. Whenever we hit the assert testing code we expand the function further and add more testcases.

2021-12-09 07:51 UTC, bcardosolopes commented on clang/lib/CIR/CIRGenTypes.cpp
> +    // ...
Missing assert here.

2021-12-09 07:51 UTC, bcardosolopes commented on clang/lib/CIR/CIRGenTypes.cpp
> +  // if ((forBitField && qualType->isExtIntType()) ||
I'm not too much against leaving commented code around, but unless the context is more obvious I'd say to trim this off.

2021-12-09 07:51 UTC, bcardosolopes commented on clang/lib/CIR/CIRGenTypes.cpp
> +    // ...
Wait, there's an assert on the line above! Just remove this if stmt then.

2021-12-09 07:51 UTC, bcardosolopes commented on clang/lib/CIR/CIRGenTypes.cpp
> +
Remove the extra empty line

2021-12-09 07:51 UTC, bcardosolopes commented on mlir/lib/Dialect/CIR/IR/CIRTypes.cpp
> +  if (mnemonic == "struct") {
Yea, you can add parse and print methods like we do in `CIR_PointerType`.

2021-12-09 07:51 UTC, bcardosolopes commented on mlir/include/mlir/Dialect/CIR/IR/CIRTypes.td
> +    DialectType<CIR_Dialect, CPred<"$_self.isa<StructType>()">,
Why are you not inheriting from `CIR_Type`?

2021-12-09 07:51 UTC, bcardosolopes commented on mlir/lib/Dialect/CIR/IR/CIRTypes.cpp
> +struct StructTypeStorage : public mlir::TypeStorage {
I believe this could also be auto generated by tblgen as it happens with `PointerType` in `CIROpsTypes.cpp.inc`.

2021-12-09 22:24 UTC, lanza commented on clang/lib/CIR/CIRBuilder.cpp
> +      //         getContext().getRecordType(cast<clang::RecordDecl>(decl)));
We don't have a `getModuleDebugInfo()` (or equivalent) yet to assert on. This switch for `Decl::Record` is correctly a no-op otherwise.

2021-12-09 23:09 UTC, lanza commented on clang/lib/CIR/CIRGenTypes.cpp
> +    return entry;
Good idea. I'll keep in mind as I rewrite this to account for mlir type caching where llvm doesn't

2021-12-10 00:36 UTC, bcardosolopes commented on clang/lib/CIR/CIRBuilder.cpp
> +      //         getContext().getRecordType(cast<clang::RecordDecl>(decl)));
I don't understand how this method contributes anything besides emitting functions, that's why I ask the assertion, seems misleading to get in any of these case stmts right now, should probably be an error if that happens? What am I missing?

2021-12-10 01:10 UTC, lanza commented on clang/lib/CIR/CIRBuilder.cpp
> +      //         getContext().getRecordType(cast<clang::RecordDecl>(decl)));
Oh, are you referring to why this is `emitTopLevelDecl`? The call chain is

```
ParseAST
CIRGenConsumer::HandleTopLevelDecl
CIRContext::HandleTopLevelDecl
CIRBuilder::buildTopLevelDecl
```

So any top level `RecordDecl`s ends up being set to this function. This function is analogous to `CodeGenModule::EmitTopLevelDecl`.

2021-12-10 01:25 UTC, lanza commented on mlir/include/mlir/Dialect/CIR/IR/CIRTypes.td
> +    DialectType<CIR_Dialect, CPred<"$_self.isa<StructType>()">,
Was procrastinating reading the ODS docs :p

2021-12-10 01:50 UTC, bcardosolopes commented on clang/lib/CIR/CIRBuilder.cpp
> +      //         getContext().getRecordType(cast<clang::RecordDecl>(decl)));
Yea, I got the top level part, but I'm confused with the actual codegen bits, I don't see anything being called as part of these case stmt, is that because you didn't add it in the first version? I was assuming this patch would build and be able to run the test, so I might been off LOL

2021-12-10 01:57 UTC, lanza commented on clang/lib/CIR/CIRBuilder.cpp
> +      //         getContext().getRecordType(cast<clang::RecordDecl>(decl)));
Oh, there's nothing to emit for just a top level `RecordDecl`. [Clang does the same](https://github.com/llvm/llvm-project/blob/5bba0fe12b2971a9cbc859f48ee6e6c1356c88b8/clang/lib/CodeGen/CodeGenModule.cpp#L6114). The only purpose for the `case` statement here is to prevent the `Decl::Record` case from falling into the `default` `assert(false)`.

2021-12-10 03:18 UTC, bcardosolopes commented on clang/lib/CIR/CIRBuilder.cpp
> +      //         getContext().getRecordType(cast<clang::RecordDecl>(decl)));
Oh I see now, I guess clang probably materializes only in case it's used? Is that what we wanna do? Seems fine as a starting point to me, but let's keep thinking about it. If so, where's the entry point for codegenin'g the struct then? Can you please update the comments on the case stmts explaining why it isn't expected do anything? Also, if I try this patch out am I gonna be able to run the test?

2021-12-10 23:24 UTC, lanza commented
> I think we would benefit from a smaller patch to build on top, there's too much stuff being introduced that don't contribute to the struct "hello world".

Yup, I'm going to break this apart using the write a test case -> fix failed asserts methodology. This was just putting up the bulk representation.

> Is the layout caching necessary? 

As of right now? No. I'm going to leave it out for the first `RecordDecl` patch. But the cached layout is used many times for `CodeGen`. I think I'm just going to compute it once and then use it to generate the `mlir::cir::StructType` then cache that against the `RecordDecl`. 

> It would be nice to have the name info out of the box.

Yup, will be adding that. 

> I'd suggest we keep capital names for things we are copying from codegeinfo. For example I noticed CIRBitFieldInfo members got lowered, I see we having lots of trouble in the future rewriting all of this because we factored out things upstream and since they are shared with Clang's regular LLVM codegen they will likely stay capitalized. I know this is a weird place to be, my general fuzzy rule has been: if it's related to emit/building AST I'm mostly using LLVM style, when it's creating/dealing with mlir types/ops, I use lower - it's a shitty system so I won't get picky on that.


Hmm, the pattern seems a bit vague. `CIRBuilder`, for example, is mostly lowercased. What's the tiebreaker you used to decide? It's closest relative would be `CodeGenModule`. Or do you consider it it's entirely own entity and thus the lower case?

2021-12-11 00:02 UTC, bcardosolopes commented
> Hmm, the pattern seems a bit vague. `CIRBuilder`, for example, is mostly lowercased. What's the tiebreaker you used to decide? It's closest relative would be `CodeGenModule`. Or do you consider it it's entirely own entity and thus the lower case?

The only tiebreaker I do use is on things that I'd like to be a client of instead of copying, those I try to copy with the same names (even though I usually trim off the content)

2021-12-11 01:07 UTC, lanza commented
Okay, this has no name yet. I'm intentionally leaving that out for now since that might be something we only want up ending in the vtable.

TBAA info might end up wanting to have the name in the struct, but that's another design decision we have to figure out first.

2021-12-11 04:35 UTC, bcardosolopes requested changes
This is very good, finally got a holistic view. Should be good after applying this last round of review!

2021-12-11 04:35 UTC, bcardosolopes commented on clang/lib/CIR/CIRRecordLayoutBuilder.cpp
> +    unsigned alignedBits =
You can also remove this function for now.

2021-12-11 04:35 UTC, bcardosolopes commented on clang/lib/CIR/CIRRecordLayoutBuilder.cpp
> +  /// Constructs a MemberInfo instance from an offset and an mlir::Type
This one also doesn't seem to be used just yet

2021-12-11 04:35 UTC, bcardosolopes commented on clang/lib/CIR/CIRRecordLayoutBuilder.cpp
> +    if (member.data)
Not clear to me what should happen if `member.data` isn't there, do you have a testcase to add? If not I recommend putting an assert there and dropping the `if`!

2021-12-11 04:35 UTC, bcardosolopes commented on clang/lib/CIR/CIRRecordLayoutBuilder.cpp
> +      if (member.fieldDecl)
Same question here, what happens if `member.fieldDecl` is null?

2021-12-11 04:35 UTC, bcardosolopes commented on clang/lib/CIR/CIRRecordLayoutBuilder.cpp
> +    if (member.kind == MemberInfo::InfoKind::Field) {
Because of the assert below you don't need this extra `if` scope.

2021-12-11 04:35 UTC, bcardosolopes commented on clang/lib/CIR/CIRRecordLayoutBuilder.cpp
> +  llvm::DenseMap<const clang::FieldDecl *, unsigned> fields;
I see now what `fields` is for, I see where this is going for bitfields hehe

2021-12-11 04:35 UTC, bcardosolopes commented on clang/test/CIR/CodeGen/struct.c
> +  int a;
Can you add another struct with more than one field and a mix of types? (assuming it's working)

2021-12-11 04:35 UTC, bcardosolopes commented on clang/test/CIR/CodeGen/struct.c
> +
Random note: one next interesting patch could be to add a simple recursive struct.

2021-12-11 04:35 UTC, bcardosolopes commented on mlir/include/mlir/Dialect/CIR/IR/CIRTypes.td
> +    Each unique clang::RecordDecl is mapped to a `cir.struct` and any object in
Even though we are emitting from Clang AST, CIR could be built in other ways and might be better to be generic here and not mention `clang::RecordDecl`.

2021-12-11 04:35 UTC, bcardosolopes commented on mlir/include/mlir/Dialect/CIR/IR/CIRTypes.td
> +    ArrayRefParameter<"mlir::Type", "members">:$members,
Will this later also track methods? Have you given some thought about having different arrays for data vs functions? This is ok for now, just wondering

2021-12-11 04:35 UTC, bcardosolopes commented on mlir/include/mlir/Dialect/CIR/IR/CIRTypes.td
> +    Type onlyMember; // TODO: fix this!
What's wrong here?

2021-12-11 04:35 UTC, bcardosolopes commented on mlir/include/mlir/Dialect/CIR/IR/CIRTypes.td
> +def CIR_StructType : CIR_Type<"Struct", "struct"> {
Nice job with the full tablegen thing!

2021-12-11 04:35 UTC, bcardosolopes commented on mlir/lib/Dialect/CIR/IR/CIRTypes.cpp
> +  addTypes<BoolType, PointerType, StructType>();
Very important!

2021-12-11 04:35 UTC, bcardosolopes commented on clang/test/CIR/CodeGen/struct.c
> +// CHECK-NEXT:   %0 = cir.alloca !cir.struct<"struct.Foo",i32>, !cir.ptr<!cir.struct<"struct.Foo",i32>>, [uninitialized] {alignment = 4 : i64}
More future work: hoist the type out to a TypeAlias and have a terse description, can you add this TODO somewhere in this patch?

2021-12-16 02:07 UTC, lanza commented on clang/test/CIR/CodeGen/struct.c
> +
Yup, I figure the approach going forward would be incrementally adding features to this test case!

2021-12-16 02:10 UTC, lanza commented on clang/test/CIR/CodeGen/struct.c
> +// CHECK-NEXT:   %0 = cir.alloca !cir.struct<"struct.Foo",i32>, !cir.ptr<!cir.struct<"struct.Foo",i32>>, [uninitialized] {alignment = 4 : i64}
Done!

2021-12-16 02:15 UTC, lanza commented on mlir/include/mlir/Dialect/CIR/IR/CIRTypes.td
> +    ArrayRefParameter<"mlir::Type", "members">:$members,
Yup, this was why I mentioned that SIL keeps around the AST `ClassDecl`s and even serializes/deserializes them as part of it's file format. When a SIL pass needs to know information about the class it goes to the SIL module and finds the AST ClassDecls that it contains and refers to that for this information. I was thinking maybe we could mimic that by literally just copying the contents of a `RecordDecl` to a region in MLIR. Shrug, we'll have to play with these ideas.

2021-12-16 02:15 UTC, lanza commented on mlir/include/mlir/Dialect/CIR/IR/CIRTypes.td
> +    Type onlyMember; // TODO: fix this!
This was why I only had one member type in the test case. I was only parsing a single member. Using a while statement written in a string in tbd feels gross, but I guess it'll suffice.

2021-12-16 02:16 UTC, closed without merging