Implement manual exclusion of patterns from type deduction
bcardosolopes/llvm-project pull request #6
Opened 2020-10-06 16:42 UTC by dansarginson

- '!' syntax to exclude individual patterns from type deduction
- Permitted for compound statements only, bare statements disallowed
- New test cases added for parsing and sema

2020-10-14 00:17 UTC, bcardosolopes requested changes
Sorry for the delay here!

2020-10-14 00:17 UTC, bcardosolopes commented on clang/include/clang/AST/Stmt.h
> +    unsigned PatternStmtExcludedFromTypeDeduction : 1;
Can you simplify the name a bit? I suggest `SkipTypeDeduction`. (We should probably rename `PatternStmtHasPatternGuard` at some point as well).

2020-10-14 00:17 UTC, bcardosolopes commented on clang/lib/Sema/SemaExprCXX.cpp
> +  // excluded from type deduction.
Nice comment!

2020-10-14 00:17 UTC, bcardosolopes commented on clang/lib/Sema/SemaExprCXX.cpp
> +  }
Instead of putting all this logic here, I'd prefer if instead you change `getPatternExprType` to return `QualType()` in case `excludedFromTypeDeduction()` is true. Then in this loop just hit continue when that's the case. If the `!{}` pattern is the only pattern and we don't have a resulting type, we should emit an error (or deduce `void` in case I'm having the wrong reading of our discussion).

2020-10-14 01:01 UTC, bcardosolopes commented
Do you plan to add codegen support in a followup commit? Please update the title to make it more obvious that this only covers parsing and sema?

2020-10-21 16:11 UTC, dansarginson commented
I'm worried this might be a silly question but... does this interact with codegen? Doesn't this just limit freedom for what's already implemented and provide diagnostics for the new limitations?

2020-10-21 18:16 UTC, bcardosolopes commented
> I'm worried this might be a silly question but... does this interact with codegen? Doesn't this just limit freedom for what's already implemented and provide diagnostics for the new limitations?

I'm mostly curious about the `std::terminate` part, you probably want to add codegen for that at some point. If not for this commit would be nice to have a codegen test that checks the call is not there, so that when you add it you can just flip the test. You can look at `getClangCallTerminateFn` in `lib/CodeGen/ItaniumCXXABI.cpp` for an example on how to do that.

2020-11-12 19:50 UTC, dansarginson commented on clang/lib/Sema/SemaExprCXX.cpp
> +  }
Done

2020-11-12 19:51 UTC, dansarginson commented on clang/include/clang/AST/Stmt.h
> +    unsigned PatternStmtExcludedFromTypeDeduction : 1;
Done

2020-11-12 19:51 UTC, dansarginson commented on clang/include/clang/AST/Stmt.h
> +  SourceLocation ExclaimLoc;
Done

2020-11-12 19:51 UTC, dansarginson commented on clang/test/Parser/cxx-inspect.cpp
> +    __ => !{}; // exclude only pattern
Agreed, this is now an error with a diagnostic and a test

2020-11-18 17:25 UTC, bcardosolopes requested changes
Thanks for improving this! It looks good, just a few minor changes and this is ready to go.

2020-11-18 17:25 UTC, bcardosolopes commented on clang/lib/Sema/SemaExprCXX.cpp
> +  if (!IE->hasExplicitResultType()) {
I believe this can be simplified a bit further:

```
if (!IE->hasExplicitResultType() && ResTy.isNull()) {
  Diag(IE->getBeginLoc(), diag::err_typecheck_no_valid_return_type);
  return ExprError();
}
IE->setType(ResTy);
```

2020-11-18 17:25 UTC, bcardosolopes commented on clang/lib/Sema/SemaExprCXX.cpp
> +    } else {
No need to wrap this into the `else` here, since the previous block "early resumes"

2020-11-18 18:16 UTC, dansarginson commented on clang/lib/Sema/SemaExprCXX.cpp
> +  if (!IE->hasExplicitResultType()) {
Nice! Done

2020-11-18 18:16 UTC, dansarginson commented on clang/lib/Sema/SemaExprCXX.cpp
> +    } else {
And done

2020-11-18 18:41 UTC, bcardosolopes approved these changes
LGTM

2020-11-18 18:41 UTC, merged